name: GlomExtractor
channels:
  - anaconda
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alsa-lib=1.2.8
  - aom=3.5.0
  - asttokens=3.0.0
  - attr=2.5.2
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2025.12.2
  - cairo=1.16.0
  - comm=0.2.3
  - dav1d=1.2.1
  - dbus=1.13.18
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - ffmpeg=5.1.2
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freeglut=3.2.2
  - freetype=2.13.3
  - fribidi=1.0.16
  - gdk-pixbuf=2.42.10
  - geos=3.10.6
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - glib=2.84.4
  - glib-tools=2.84.4
  - gmp=6.3.0
  - gnutls=3.7.9
  - graphite2=1.3.14
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - gstreamer-orc=0.4.42
  - harfbuzz=6.0.0
  - hdf5=1.14.0
  - icu=70.1
  - importlib-metadata=8.7.0
  - ipykernel=7.0.1
  - ipython=8.37.0
  - jack=1.9.22
  - jasper=2.0.33
  - jedi=0.19.2
  - jpeg=9f
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libaec=1.1.3
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libavif=0.11.1
  - libblas=3.9.0
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libcurl=8.16.0
  - libdb=6.2.32
  - libdeflate=1.22
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.4
  - libflac=1.5.0
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgcrypt=1.11.2
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.84.4
  - libglu=9.0.0
  - libgomp=15.2.0
  - libgpg-error=1.58
  - libiconv=1.18
  - libidn2=2.3.8
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.57.0
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopencv=4.7.0
  - libopenjpeg=2.5.4
  - libopus=1.6.1
  - libpciaccess=0.18
  - libpng=1.6.54
  - libpq=15.2
  - libprotobuf=3.21.12
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=252
  - libtasn1=4.21.0
  - libtiff=4.5.1
  - libtool=2.4.7
  - libudev1=253
  - libunistring=1.3
  - libuuid=1.41.5
  - libva=2.18.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp-base=1.6.0
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.7
  - mpg123=1.32.9
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - nspr=4.37
  - nss=3.89.1
  - numexpr=2.11.0
  - opencv=4.7.0
  - openh264=2.3.1
  - openjpeg=2.5.2
  - openslide=3.4.1
  - openssl=3.0.18
  - p11-kit=0.24.1
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pure_eval=0.2.3
  - py-opencv=4.7.0
  - pygments=2.19.2
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - pyzmq=27.1.0
  - qt-main=5.15.6
  - readline=8.3
  - setuptools=80.9.0
  - shapely=2.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - svt-av1=1.4.1
  - tk=8.6.14
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - wcwidth=0.2.14
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xmltodict=0.14.2
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xorgproto=2024.1
  - xorg-xproto=7.0.31
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - affine==2.4.0
      - annotated-types==0.7.0
      - asciitree==0.3.3
      - attrs==25.4.0
      - boto3==1.42.34
      - botocore==1.42.34
      - cachetools==6.2.5
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - cloudpickle==3.1.2
      - contourpy==1.3.2
      - ctk-cli==1.5
      - cycler==0.12.1
      - dask==2024.10.0
      - dask-expr==1.1.16
      - defusedxml==0.7.1
      - dicomweb-client==0.59.3
      - diskcache==5.6.3
      - distributed==2024.10.0
      - fasteners==0.20
      - fonttools==4.61.1
      - fsspec==2026.1.0
      - gdal==3.12.1.1
      - girder-client==3.2.11
      - girder-slicer-cli-web==1.5.14
      - glymur==0.14.4.1
      - greenlet==3.3.1
      - histomicstk==1.4.0
      - idna==3.11
      - imagecodecs==2025.3.30
      - imagecodecs-numcodecs==2025.3.30
      - imageio==2.37.2
      - jinja2==3.1.6
      - jmespath==1.1.0
      - joblib==1.5.3
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - large-image==1.33.5
      - large-image-converter==1.33.5
      - large-image-source-bioformats==1.33.5
      - large-image-source-deepzoom==1.33.5
      - large-image-source-dicom==1.33.5
      - large-image-source-dummy==1.33.5
      - large-image-source-gdal==1.33.5
      - large-image-source-mapnik==1.33.5
      - large-image-source-multi==1.33.5
      - large-image-source-nd2==1.33.5
      - large-image-source-ometiff==1.33.5
      - large-image-source-openjpeg==1.33.5
      - large-image-source-openslide==1.33.5
      - large-image-source-pil==1.33.5
      - large-image-source-rasterio==1.33.5
      - large-image-source-test==1.33.5
      - large-image-source-tiff==1.33.5
      - large-image-source-tifffile==1.33.5
      - large-image-source-vips==1.33.5
      - large-image-source-zarr==1.33.5
      - lazy-loader==0.4
      - locket==1.0.0
      - lxml==6.0.2
      - mapnik==4.2.0.1
      - markupsafe==3.0.3
      - marshmallow==3.26.2
      - matplotlib==3.10.8
      - msgpack==1.1.2
      - nd2==0.11.2
      - networkx==3.4.2
      - nimfa==1.4.0
      - numcodecs==0.13.1
      - numpy==2.2.6
      - ome-types==0.6.3
      - opencv-python-headless==4.13.0.90
      - openslide-bin==4.0.0.11
      - openslide-python==1.4.3.1
      - palettable==3.3.3
      - partd==1.4.2
      - pyarrow==23.0.0
      - pycparser==3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.11.0
      - pydicom==3.0.1
      - pylibtiff==0.7.0.4.7.1
      - pyparsing==3.3.2
      - pyproj==3.7.1
      - python-bioformats==4.1.0.8.4.0.1
      - python-javabridge==4.0.4.1
      - pyvips==3.1.1.8.18.0
      - pyyaml==6.0.3
      - rasterio==1.4.4
      - referencing==0.37.0
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - resource-backed-dask-array==0.1.0
      - retrying==1.4.2
      - rpds-py==0.30.0
      - s3transfer==0.16.0
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sortedcontainers==2.4.0
      - sqlalchemy==2.0.46
      - tblib==3.2.2
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tifftools==1.7.0
      - toolz==1.1.0
      - typing-inspection==0.4.2
      - universal-pathlib==0.2.6
      - urllib3==2.6.3
      - wsidicom==0.29.0
      - xsdata==26.1
      - zarr==2.18.3
      - zict==3.0.0
